version: "3.8"
services:
  nginx:
    build: .
    volumes:
      - ./test/nginx.conf:/etc/nginx/nginx.conf
    entrypoint: ["/usr/sbin/nginx", "-g", "daemon off;"]
  sut:
    image: amazonlinux:2
    command: ["/usr/bin/curl", "-f", "nginx/hello"]
    depends_on:
      - nginx
